#! /bin/sh
### BEGIN INIT INFO
# Provides:          halt
# Required-Start:
# Required-Stop:
# Default-Start:
# Default-Stop:      0
# Short-Description: Execute the halt command.
# Description:
### END INIT INFO




sudo echo 18 > /sys/class/gpio/export
#echo 1 > /sys/class/gpio/gpio17/value
sudo echo "out" > /sys/class/gpio/gpio18/direction
sudo echo 1 > /sys/class/gpio/gpio18/value
sleep 2
